  query{
    categories{
      id
      name
      icon
      img
      description
      slug
    }
    # recipes{
    #   name
    #   id
    #   category{
    #     id
    #     slug
    #   }
    # }
  }
